### ISSUE TITLE
Testing on localhost

### ISSUE THREAD

**Issue by mpbl** [radical-collaboration/hpc-workflows#47]
Hi,

As I was adapting Vivek's script in simpy, I encountered the following problem:
I wrote a simple example to be run on my local machine to make it easier to debug.

According to the entk documentation the resource has to be named ```local.localhost```.
I came up with the following:
```yaml
    resources:
      resource: local.localhost
      walltime: 10 # minutes
      cores: 4  # width of the pilot job
      # gpus: 0  # width of the pilot job
      project: 'GEO111'  # also tried None, "None"
      schema: 'local'
      # queue: 'batch'
```

The issue is that:
```bash
BadParameter: 'JobDescription.Project' (geo111) is not supported by adaptor saga.adaptor.shell_job
```

but that the entk checks for ```project``` to be present in the resource description:
```
Failed to validate resource description, error: Error: Key project does not exist in the resource description
```

Do you know any way to get past this problem?

Thanks,

Matthieu
